BulletJournal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),
    path('', include('presentation.urls')),
    path('yourBulletJournal/', include('YearMonthDay.urls')),
]

YearMonthDay/urls.py
from django.urls import path, re_path
from YearMonthDay import views


app_name = 'YearMonthDay'

urlpatterns = [
    path('yourYear/', views.yourYear, name = 'yourYear'),
    path('yourGoals/', views.yourGoals, name = 'yourGoals'),
    path('yourGoals/delete/<int:id>/', views.deleteGoal, name = 'deleteGoal'),
    path('yourGoals/update/<int:id>/', views.updateGoal, name = 'updateGoal'),
    path('yourYear/checkTask/', views.checkTask, name = 'checkTask'),
    re_path(r'^yourYear/deleteImportant/(?P<month>[A-Za-z]+)/(?P<number>\d+)/$', views.deleteImportant, name='deleteImportant'),
    re_path(r'^yourYear/(?P<mes>[A-Za-z0-9_-]+)/$', views.yourMonth, name = 'yourMonth'),
    re_path(r'^yourYear/migrate/(?P<model>[A-Za-z]+)/(?P<id>\d+)/$', views.migrate, name = 'migrate'),
    re_path(r'^yourYear/(?P<mes>[A-Za-z]+)/(?P<dia>\d+)/$', views.mesdia, name='myDay'),
    re_path(r'^yourYear/delete/(?P<model>[A-Za-z]+)/(?P<id>\d+)/$', views.delete, name = 'delete'),
    
    
]

presentation/urls.py
from django.urls import path
from presentation import views

app_name = 'presentation'

urlpatterns = [
    path('', views.greetings, name="greetings"),
]

users/urls.py
from django.urls import path
from .views import MyAccountPageView, CustomPasswordChangeView

urlpatterns = [
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('my-account/', MyAccountPageView.as_view(), name='my-account'), 
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    {% block styles %}
    {% endblock %}
    <!--Js bootstrap -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="padding-top: 50px;">
    <nav class="navbar fixed-top navbar-dark bg-primary">
        <a class="navbar-brand" style="margin-left:20px;" href="{% url 'presentation:greetings' %}">Bullet Journal</a>
        <div class="content-nav" style="margin: 0 auto;">
        {% if user.is_authenticated %}    
        <a class="navbar-brand" href="{% url 'YearMonthDay:yourYear' %}">My Year</a>
        <a class="navbar-brand" href="{% url 'YearMonthDay:yourGoals' %}">My Goals</a>
        <a class="navbar-brand" href="{% url 'my-account' %}">My Account</a>
        {%endif%}
        </div>
        {% if user.is_authenticated %}
        <span style="display: inline-block; margin-right:10px; color:white;font-style: italic;">Hi, {{user.username}}</span>
        {% endif %}
        <div class="login-nav" style="float:right; margin-right:40px;">
            {% if user.is_authenticated %}
            <form action="{% url 'account_logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" 
                style="border:none; background-color:rgb(13,110,253); color:white; font-size: large;">Log out</button>
            </form>
            {% else %} 
            <a class="navbar-brand" href="{% url 'account_login' %}">Login</a>
            <a class="navbar-brand" href="{% url 'account_signup' %}">Sign up</a>
            {%endif %}
        </div>
    </nav>
    {% block content %}
    
    {% endblock %}
    
</body>
</html>