BulletJournal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),
    path('', include('presentation.urls')),
    path('yourBulletJournal/', include('YearMonthDay.urls')),
]

YearMonthDay/urls.py
from django.urls import path, re_path
from YearMonthDay import views


app_name = 'YearMonthDay'

urlpatterns = [
    path('yourYear/', views.yourYear, name = 'yourYear'),
    path('yourGoals/', views.yourGoals, name = 'yourGoals'),
    path('yourGoals/delete/<int:id>/', views.deleteGoal, name = 'deleteGoal'),
    path('yourGoals/update/<int:id>/', views.updateGoal, name = 'updateGoal'),
    path('yourYear/checkTask/', views.checkTask, name = 'checkTask'),
    re_path(r'^yourYear/deleteImportant/(?P<month>[A-Za-z]+)/(?P<number>\d+)/$', views.deleteImportant, name='deleteImportant'),
    re_path(r'^yourYear/(?P<mes>[A-Za-z0-9_-]+)/$', views.yourMonth, name = 'yourMonth'),
    re_path(r'^yourYear/migrate/(?P<model>[A-Za-z]+)/(?P<id>\d+)/$', views.migrate, name = 'migrate'),
    re_path(r'^yourYear/(?P<mes>[A-Za-z]+)/(?P<dia>\d+)/$', views.mesdia, name='myDay'),
    re_path(r'^yourYear/delete/(?P<model>[A-Za-z]+)/(?P<id>\d+)/$', views.delete, name = 'delete'),
    
    
]

users/urls.py
from django.urls import path
from .views import MyAccountPageView, CustomPasswordChangeView

urlpatterns = [
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('my-account/', MyAccountPageView.as_view(), name='my-account'), 
    
]

YearMonthDay/models.py
from django.db import models
from django.conf import settings

class Goal(models.Model):
    goal = models.CharField(max_length=100)
    year = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='goals', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.goal

class Year(models.Model):
    year = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='years', on_delete=models.CASCADE, null=True, blank=True)
    #days

    def __str__(self):
        return str(self.year)

class Day(models.Model):
    #The days will be different depending its foreignKey
    year = models.ForeignKey(Year, related_name='days', on_delete=models.CASCADE, null=True, blank=True)
    mes = models.CharField(max_length=20, null=True)
    number = models.CharField(max_length=20)
    numberInt = models.IntegerField(null=True, blank=True)
    important = models.CharField(max_length=100, null=True, blank=True)
    importantIsDone = models.BooleanField(default=False, blank=True, null=True)
    #tasks
    #events
    #notes

    def __str__(self):
        return self.mes + ' ' + self.number

class Task(models.Model):
    to_do = models.CharField(max_length=100)
    last_update = models.DateField(auto_now=True)
    day = models.ForeignKey(Day, related_name='tasks', on_delete= models.CASCADE, null=True, blank=True)
    done = models.BooleanField(default=False)

    def class_name(self):
        return self.__class__.__name__ 

    def __str__(self):
        return self.to_do

class Event(models.Model):
    desc = models.CharField(max_length=50)
    day = models.ForeignKey(Day, related_name='events', on_delete= models.CASCADE, null=True, blank=True)
    done = models.BooleanField(default=False) 

    def class_name(self):
        return self.__class__.__name__ 

    def __str__(self):
        return self.desc

class Note(models.Model):
    text = models.CharField(max_length=100)
    day = models.ForeignKey(Day, related_name='notes', on_delete= models.CASCADE, null=True, blank=True)

    def class_name(self):
        return self.__class__.__name__ 

    def __str__(self):
        return self.text




# Create your models here.

YearMonthDay/forms.py
from django import forms
from YearMonthDay.models import * 

class GoalForm(forms.ModelForm):
    #validaciones
    #campos añadidos al formulario

    #meta, fields, label, widgets

    class Meta:
        model = Goal

        fields = ['goal',]

        labels = {
            'goal': 'Goal ',
        }

YearMonthDay/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http import JsonResponse
from django.apps import apps
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from YearMonthDay.models import * 
from YearMonthDay.forms import *
import datetime
import calendar

@login_required()
def yourGoals(request):
    if request.method == 'GET':

        context = {
            'form': GoalForm(),
        }
        
        return render(request, 'YearMonthDay/yourGoals.html', context=context)

    if request.method == 'POST':
        date = datetime.datetime.now().date()
        year = date.strftime("%Y")
        user = request.user
        usermodel = get_user_model()
        userObj = usermodel.objects.get(id=user.id)

        if not userObj.years.filter(year=int(year)).exists():
            Year.objects.create(year=int(year), user = userObj)
        goalData = request.POST.get('goal')
        Goal.objects.create(goal=goalData, year=year, user=userObj)
        goal = Goal.objects.last()
        return JsonResponse({'goal': {'id': goal.id , 'goal': goal.goal}})

@login_required()
def deleteGoal(request, id):
    user = request.user
    usermodel = get_user_model()
    userObj = usermodel.objects.get(id=user.id)

    if request.method == 'GET':
        
        context = {
            'goal' : userObj.goals.filter(id=id).first(),
        }
        
        return render(request, 'YearMonthDay/deleteGoal.html', context=context)
    
    if request.method == 'POST':

        goal = userObj.goals.filter(id=id).first()
        goal.delete()

        return redirect(reverse('YearMonthDay:yourGoals'))

@login_required()
def updateGoal(request, id):

    user = request.user
    usermodel = get_user_model()
    userObj = usermodel.objects.get(id=user.id)

    if request.method == 'GET':
        goal = userObj.goals.filter(id=id).first()
        form = GoalForm(instance=goal)

        context = {
            'formModel' : form,
        }

        return render(request, 'YearMonthDay/updateGoal.html', context)
    
    if request.method == 'POST':
        goal = Goal.objects.get(id=id)
        #look at this
        form = GoalForm(request.POST, instance=goal)
        if form.is_valid():
            #only if the form is valid
            form.save()
            return redirect(reverse('YearMonthDay:yourGoals'))
        else:
            return render(request, 'YearMonthDay/updateGoal.html', {'formModel'  : form})
    
@login_required()
def yourYear(request):
    if request.method == 'GET':
        #creating a year obj if not was created yet
        user = request.user
        usermodel = get_user_model()
        userObj = usermodel.objects.get(id=user.id)
        date = datetime.datetime.now().date()
        year = date.strftime("%Y")
        month = date.strftime("%m")
        if not Year.objects.filter(year=year, user=userObj).exists():
            Year.objects.create(year=year, user=userObj)
        #creating each month of the year
        myarr = []
        for i in range(1, 13, 1):
            mc = calendar.HTMLCalendar()
            mc = mc.formatmonth(int(year), int(i))
            monthName = calendar.month_name[i]
            myarr.append({'mc': mc, 'monthName': monthName})
        return render(request, 'YearMonthDay/year.html', context={'months': myarr, 'year': year})

@login_required()
def yourMonth(request, mes):
    
    if request.method == 'GET':
        month = getOnlyWords(mes)
        year = getOnlyInt(mes)
        month_number = datetime.datetime.strptime(month[:3], '%b').month
        daysInMonth= calendar.monthrange(year, month_number)[1]
        #the date imput requiered this 
        if len(str(month_number)) == 1:
            month_number = '0' + str(month_number)
        #Creating all days of the month
        user = request.user
        yearObj = Year.objects.get(year=int(year), user__id=user.id)
        for i in range(1, daysInMonth + 1, 1):
            if Day.objects.filter(year=yearObj, mes=month, number=i).exists():
                pass
            else:
                Day.objects.create(year=yearObj, mes=month, number=i, numberInt=i)
        days10 = Day.objects.filter(year=yearObj, mes=month).order_by('numberInt')[:10]
        days20 = Day.objects.filter(year=yearObj, mes=month).order_by('numberInt')[10:20]
        daysRest = Day.objects.filter(year=yearObj, mes=month).order_by('numberInt')[20:]

        context = {
            'monthStr': month,
            'monthInt': month_number,
            'year': year,
            'daysOfMonth': daysInMonth,
            'days10': days10,
            'days20': days20,
            'daysRest': daysRest,
        }
        return render(request, 'YearMonthDay/month.html', context=context)
    
    if request.method == 'POST':
        importantTask = request.POST.get('importantTask')
        date = request.POST.get('day')
        dateStr = date.replace('-', ' ')
        dateList = dateStr.split()
        objDate = datetime.datetime(int(dateList[0]), int(dateList[1]), int(dateList[2]))
        #getting obj year
        date = datetime.datetime.now().date()
        year = date.strftime("%Y")
        user = request.user
        yearObj = Year.objects.get(year=int(year), user__id=user.id)
        #getting day number from objDate
        day = int(objDate.strftime("%d"))
        day = Day.objects.get(year=yearObj, mes=mes, number=day)
        day.important = importantTask
        day.save()
        return JsonResponse({'day': {'id': day.numberInt, 'important': day.important, 'month': day.mes}})
        
@login_required()
def mesdia(request, mes, dia):

    if request.method == 'GET':
        date = datetime.datetime.now().date()
        year = date.strftime("%Y")
        user = request.user
        yearObj = Year.objects.get(year=int(year), user__id=user.id)
        if Day.objects.filter(year=yearObj, mes=mes, number=dia).exists():
            day = Day.objects.get(year=yearObj, mes=mes, number=dia)
        else:
            day = Day.objects.create(year=yearObj, mes=mes, number=dia, numberInt=dia)

        context = {
            'dia': day,
        }

        return render(request, 'YearMonthDay/day.html', context=context)

    if request.method == 'POST':
        if request.headers['x-requested-with'] == 'XMLHttpRequest':
            date = datetime.datetime.now().date()
            year = date.strftime("%Y")
            user = request.user
            yearObj = Year.objects.get(year=int(year), user__id=user.id)
            instanceDay = Day.objects.get(year=yearObj, mes=mes, number=dia)
            if request.POST.get('to_do', False):
                task = request.POST['to_do']
                Task.objects.create(to_do=task, day=instanceDay)
                data = list(instanceDay.tasks.all().values())
            if request.POST.get('event', False):
                event = request.POST['event']
                Event.objects.create(desc=event, day=instanceDay)
                data = list(instanceDay.events.all().values())
            if request.POST.get('note', False):
                note = request.POST['note']
                Note.objects.create(text=note, day=instanceDay)
                data = list(instanceDay.notes.all().values())
            return JsonResponse({'objects': data})

@login_required()
def migrate(request, model, id):

    if request.method == 'GET':

        Model = apps.get_model('YearMonthDay', model)
        obj = Model.objects.get(id=id)
        month = obj.day.mes
        numberday =obj.day.numberInt 
        month_number = datetime.datetime.strptime(month[:3], '%b').month
        date = datetime.datetime.now().date()
        year = date.strftime("%Y")
        daysInMonth= calendar.monthrange(int(year), month_number)[1]
        #the date imput requiered this 
        if len(str(month_number)) == 1:
            month_number = '0' + str(month_number)
        print(month_number)
        print(daysInMonth)

        context = {
            'obj': Model.objects.get(id=id),
            'year': year,
            'monthNum': month_number,
            'daysInMonth': daysInMonth,
            'mes': month,
            'number': numberday,
            }

        return render(request, 'YearMonthDay/migrate.html', context=context)

    else:
        Model = apps.get_model('YearMonthDay', model)
        obj = Model.objects.get(id=id)
        previusDay = obj.day
        #to contruct the reverse url
        dayUrl = previusDay.number
        monthUrl = previusDay.mes
        #getting the data from Post
        date = request.POST.get('dateToMigrate')
        #format data for datetime object
        dateStr = date.replace('-', ' ')
        dateList = dateStr.split()
        print('*'*90)
        print(dateList)
        objDate = datetime.datetime(int(dateList[0]), int(dateList[1]), int(dateList[2]))
        #getting month name and day number from objDate
        month = objDate.strftime("%B") 
        day = int(objDate.strftime("%d"))
        #changing the task foreign key
        date = datetime.datetime.now().date()
        year = date.strftime("%Y")
        user = request.user
        yearObj = Year.objects.get(year=int(year), user__id=user.id)
        if Day.objects.filter(year=yearObj, mes=month, number=day).exists():
            instance = Day.objects.get(year=yearObj, mes=month, number=day)
        else:
            instance = Day.objects.create(year=yearObj, mes=month, number=day, numberInt=day)
        obj.day = instance
        obj.save()
        return redirect(reverse('YearMonthDay:myDay', kwargs={'mes':monthUrl, 'dia': dayUrl}))
        
@login_required()
def delete(request, model, id):
    #obj represent a task object, event object or note.
    Model = apps.get_model('YearMonthDay', model)
    obj = Model.objects.get(id=id)
    previusDay = obj.day
    #to contruct the reverse url
    dayUrl = previusDay.number
    monthUrl = previusDay.mes
    obj.delete()

templates/YearMonthDay/deleteGoal.html
{% extends 'base.html'%} 
{% load static %} 
{% block styles %} <link rel="stylesheet" href="{% static 'css/YearMonthDay/deleteGoal.css' %}"> {% endblock %}
{% block title %}Delete your goal{%endblock%}

{%block content%} 
<div class="container">
    <div class="card border-primary m-auto mb-3">
        <div class="card-header text-center">Are you sure that you want to delete this goal?</div>
        <div class="card-body">
        <p>{{goal}}</p>
        <form action="" method="post">
            {% csrf_token %}
            <div class="actions">
                <button type="submit" class="btn btn-danger">Delete</button>
                <a href="{% url 'YearMonthDay:yourGoals' %}" class="btn btn-success">Get Back!</a>
            </div>
        </form>
        </div>
    </div>
</div>

{%endblock%} 

templates/YearMonthDay/migrate.html
{% extends 'base.html'%}
{% load static %} 
{% block styles %} <link rel="stylesheet" href="{% static 'css/YearMonthDay/migrate.css' %}"> {% endblock %}
{% block title %}Migrate Task{%endblock%}

{% block content %} 

<div class="container">
    <div class="card border-primary m-auto mb-3" style="max-width: 30rem">
        <div class="card-header text-center text">Migrate {{obj.class_name|lower}}</div>
        <div class="card-body">
            {% if obj.done == False or obj.class_name == 'Note'%}
            <p class="card-text text-center">Please select a day to migrate your {{obj.class_name|lower}}.</p>
            <form method="post" action="">
            {% csrf_token %}
            <input type="date" id="date" name="dateToMigrate" 
            min="{{year}}-{{monthNum}}-1" max="{{year}}-{{monthNum}}-{{daysInMonth}}">
            <button type="submit" class="btn btn-info">Migrar</button>
            <a href="{% url 'YearMonthDay:myDay' mes=mes dia=number %}" class="btn btn-danger">Cancel</a>
            </form>
            {% else %}
            <p class="card-text">
            <h3>The {{obj.class_name|lower}} is already done. You cannot migrate it.</h3>
            </p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/YearMonthDay/migrateTask.html
{% extends 'base.html'%}

{% block title %}Migrate Task{%endblock%}

{% block content %} 

<div>
    <h3>Task: {{task.to_do}}</h3>
    <h3>Day: {{task.days.mes}} {{task.days.number}}</h3>
    <form action="" method="post">
        {% csrf_token %}
        <label for="date">Pick a date to migrate your task</label>
        <input type="date" id="date" name="dateToMigrate">
        <button type="submit" class="btn btn-info">Migrar</button>
    </form>
</div>

{% endblock %}

templates/YearMonthDay/month.html
{% extends 'base.html'%} 
{% load static %} 
{% block styles %} <link rel="stylesheet" href="{% static 'css/YearMonthDay/month.css' %}"> {% endblock %}
{% block title %}Your Month{%endblock%}

{%block content%} 

<div class="content-month">
    <h3 id="month">{{monthStr}}</h3>
    <h3 id="instruction">Write one important task or event for each day of the month</h3>
    <form action="" method="post" id="form">
        <input type="text" id="inputText" name="importantTask" autofocus>
        <input type="date" id="date" name="day" 
        min="{{year}}-{{monthInt}}-01" max="{{year}}-{{monthInt}}-{{daysOfMonth}}" required>
        <button type="button" onclick="saveData()" id="button">Add</button>
    </form>
    <div class="content-list">
        <ol id="list">
            {% for day in days10 %} 
            <li id="li{{day.numberInt}}"> 
                {% if day.important %}
                <p id="important{{day.numberInt}}" style="display: inline-block">{{day.important|default_if_none:" " }}</p>
                <a href="{% url 'YearMonthDay:deleteImportant' number=day.numberInt month=day.mes %}" class="ancor">
                    <i class="fa fa-trash-o" aria-hidden="true" id="{{day.numberInt}}"></i></a>
                {%else%}
                <p id="important{{day.numberInt}}" style="display: inline-block">{{day.important|default_if_none:" " }}</p>
                {%endif%}
            </li>
            {% endfor %}
        </ol>
        <ol start="11" id="list2">
            {% for day in days20 %} 
            <li id="li{{day.numberInt}}">
                {%if day.important %}
                <p id="important{{day.numberInt}}" style="display: inline-block">{{day.important|default_if_none:" " }}</p>
                <a href="{% url 'YearMonthDay:deleteImportant' number=day.numberInt month=day.mes%}" class="ancor">
                    <i class="fa fa-trash-o" aria-hidden="true" id="{{day.numberInt}}"></i></a>
                {%else%}
                <p id="important{{day.numberInt}}" style="display: inline-block">{{day.important|default_if_none:" " }}</p>
                {%endif%}
            </li>
            {% endfor %}
        </ol>
        <ol start="21" id="list3">
            {% for day in daysRest %} 
            <li id="li{{day.numberInt}}">
                {% if day.important %}
                <p id="important{{day.numberInt}}" style="display: inline-block">{{day.important|default_if_none:" " }}</p>
                <a href="{% url 'YearMonthDay:deleteImportant' number=day.numberInt month=day.mes%}" class="ancor">
                    <i class="fa fa-trash-o" aria-hidden="true" id="{{day.numberInt}}"></i></a>
                {%else%}
                <p id="important{{day.numberInt}}" style="display: inline-block">{{day.important|default_if_none:" " }}</p>
                {%endif%}
            </li>
            {% endfor %}
        </ol>
    </div>
</div> 

<script>

    function setAttributes(element, attrs) {
        for(let key in attrs) {
            element.setAttribute(key, attrs[key]);
            }
        }

    function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
            }
            return cookieValue;
        }
    
    function saveData() {
        let date = document.getElementById('date').value;
        if(!date) {
            return alert('Please select a date please')
        }
        let form = new FormData(document.getElementById('form'));
        let month = document.getElementById('month');
        let list = document.getElementById('list');
        month = month.innerHTML;
        fetch(
                '/yourBulletJournal/yourYear/' + month + '/', {
                    method: 'POST',
                    body: form,
                    headers: {
                        'X-CSRFToken': getCookie('csrftoken'),
                        'X-Requested-With': 'XMLHttpRequest',
                    }
                }
            ).then(function (response) {
                return response.json();
            }).then(function (data){
                let day = data.day;
                let important = day.important;
                let id = day.id;
                let month = day.month;
                document.getElementById('important' + id).innerHTML = important;
                ancor = document.createElement('a');
                ancor.setAttribute('class', 'ancor');
                ancor.href = '/yourBulletJournal/yourYear/deleteImportant/' + month + '/' + id + '/';
                icon = document.createElement('i');
                icon.setAttribute('class', 'fa fa-trash-o')
                icon.setAttribute('aria-hidden', 'true');
                icon.setAttribute('id', id);
                ancor.appendChild(icon);
                if (document.getElementById(id) == null) {
                    document.getElementById('li' + id).appendChild(ancor);
                }
            })
    }

    items = document.getElementsByTagName('p');
    for (let i = 0; i < items.length; i++){
        if(items[i].innerHTML == " "){
            items[i].setAttribute('style', 'padding: 4px')
        }
    }

    var input = document.getElementById("inputText");
    // Execute a function when the user presses a key on the keyboard
    input.addEventListener("keypress", function(event) {
    // If the user presses the "Enter" key on the keyboard
    if (event.key === "Enter") {
        // Cancel the default action, if needed
        event.preventDefault();
        // Trigger the button element with a click
        date = document.getElementById('date').value;
        if (date) {
            document.getElementById("button").click();
            input.value = "";
        } else {
            alert("Please enter a date");
        }
        //
        
    }
});

        
</script>
{%endblock%} 

templates/YearMonthDay/updateGoal.html
{% extends 'base.html'%}
{% load static %} 
{% block styles %} <link rel="stylesheet" href="{% static 'css/YearMonthDay/updateGoal.css' %}"> {% endblock %}
{% block title %}Update Goal{%endblock%}

{% block content %} 

<div class="container">
    <div class="card border-primary m-auto mb-3" style="max-width: 30rem">
        <div class="card-header text-center">Update your goal</div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{formModel}}
                <div class="actions">
                    <button id=button type="submit" class="btn btn-primary">Update</button>
                    <a href="{% url 'YearMonthDay:yourGoals' %}" class="btn btn-danger">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/YearMonthDay/yourGoals.html
{% extends 'base.html'%} 
{% load static %} 
{% block styles %} <link rel="stylesheet" href="{% static 'css/YearMonthDay/yourGoals.css' %}"> {% endblock %}
{% block title %}Starting Your BulletJournal{%endblock%}

{%block content%} 
<div class="content-start">
        <div class="card border-primary m-auto mb-3 list-goals">
            {% if user.goals.all  %}
            <div class="card-header text-center">Here you can add new goals, modify the existings ones or delete them.</div>
            {%else%}
            <div class="card-header text-center">Write your goals for this year:</div>
            {% endif %}
            <div class="card-body">
                <form action="" method="post" id="form">
                    {% csrf_token %}
                    {{form}}
                </form>
                <button type="button" id="buttonAdd" onclick="saveData()">Add goal</button>
            <ol id="list">
                {% for goal in user.goals.all %} 
                <li>
                    <p class="paragraph_li">{{goal|capfirst}}</p>
                    <div id="container-action">
                        <a href="{% url 'YearMonthDay:deleteGoal' id=goal.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                        <a href="{% url 'YearMonthDay:updateGoal' id=goal.id %}"><i class="fa fa-pencil-square" aria-hidden="true"></i></a>
                    </div>
                </li> 
                {% endfor %}
            </ol>
        </div>
        <a href="{% url 'YearMonthDay:yourYear' %}" class="btn btn-success" id="ancor">
            {% if user.goals.all %}
            Save!
            {% else %}
            Get Start!
            {% endif %}
        </a>
    </div>
</div>

<script>

    function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
            }
            return cookieValue;
        }
    
    function saveData() {
        let value = document.getElementById('id_goal').value;
        if(!value) {
            return alert ('Add a goal please');
        }
        let form = new FormData(document.getElementById('form'));
        let lista = document.getElementById('list');
        fetch(
            '/yourBulletJournal/yourGoals/', {
                method: 'POST',
                body: form,
                headers: {
                    'X-CSRFToken': getCookie('csrftoken'),
                    'X-Requested-With': 'XMLHttpRequest',
                }
            }
            ).then(function (response) {
                return response.json();
            }).then(function (data){
                let goal = data.goal;
                let inputElement = goal.goal;
                let listElement = document.createElement("li");
                setAttributes(listElement, {"style": 'font-size:20px; font-style:italic; display:flex; justify-content:space-between;'})
                let p = document.createElement("p");
                setAttributes(p, {"style": 'max-width:85%', 'class': 'paragraph_li'})
                p.innerHTML = capitalizeFirstLetter(inputElement);
                listElement.appendChild(p);
                divElement = document.createElement("div");
                let a = document.createElement("a");
                setAttributes(a, {'href': '/yourBulletJournal/yourGoals/delete/' + goal.id})
                iconElement = document.createElement("i");
                setAttributes(iconElement, {'class': 'fa fa-trash-o', 'aria-hidden': 'true'});
                //<i class="fa fa-pencil-square" aria-hidden="true">
                a.appendChild(iconElement);
                divElement.appendChild(a);
                let ancor = document.createElement("a");
                setAttributes(ancor, {'href':'/yourBulletJournal/yourGoals/update/' + goal.id, 'style': 'margin-left: 6px'})
                iconElement = document.createElement("i");
                setAttributes(iconElement, {'class': 'fa fa-pencil-square', 'aria-hidden': 'true'});
                //<i class="fa fa-pencil-square" aria-hidden="true">
                ancor.appendChild(iconElement);
                divElement.appendChild(ancor);
                listElement.appendChild(divElement);
                lista.insertBefore(listElement, lista.firstChild);
            })
                
        }


    function addInput() {
        let goals = document.getElementsByClassName('paragraph_li');
        if(goals.length == 0) {
            alert("Please select a goal");
        } else {
            for(let i=0; i < goals.length; i++) {
            let newInput = document.createElement("input");
            setAttributes(newInput, {'type': 'hidden', 'name':'goal' + i, 'value': goals[i].innerHTML});
            let form = document.getElementById("form");
            form.appendChild(newInput);
        }
        let form = document.getElementById("form");
        form.submit();
        }
    }

    function setAttributes(element, attrs) {
        for(let key in attrs) {
            element.setAttribute(key, attrs[key]);
            }
        }
    
        
    var input = document.getElementById("id_goal");
    // Execute a function when the user presses a key on the keyboard
    input.addEventListener("keypress", function(event) {
    // If the user presses the "Enter" key on the keyboard
    if (event.key === "Enter") {
        // Cancel the default action, if needed
        event.preventDefault();
        // Trigger the button element with a click
        document.getElementById("buttonAdd").click();
        input.value = "";
    }
});


    function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
    }

</script>

{%endblock%} 